flat_money_transfer.Rmd:
  path: dev/flat_money_transfer.Rmd
  state: active
  R:
  - R/costsplitter.R
  - R/minimize_payments.R
  - R/function-to-give-you-amount-each-has-to-pay.R
  tests:
  - tests/testthat/test-minimize_payments.R
  - tests/testthat/test-costsplitter.R
  vignettes: vignettes/divide-costs-fairly-amongst-friends.Rmd
  inflate:
    flat_file: dev/flat_money_transfer.Rmd
    vignette_name: Divide costs fairly amongst friends
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: true
