flat_money_transfer.Rmd:
  path: dev/flat_money_transfer.Rmd
  state: active
  R:
  - R/change_categorical_to_numeric.R
  - R/get_stats.R
  - R/read_data.R
  tests:
  - tests/testthat/test-read_data.R
  - tests/testthat/test-change_categorical_to_numeric.R
  - tests/testthat/test-get_stats.R
  vignettes: vignettes/divide-costs-fairly-amongst-friends.Rmd
  inflate:
    flat_file: dev/flat_money_transfer.Rmd
    vignette_name: Divide costs fairly amongst friends
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: true
