flat_money_transfer.Rmd:
  path: dev/flat_money_transfer.Rmd
  state: active
  R:
  - R/cat_to_num.R
  - R/check_costs.R
  - R/check_participants.R
  - R/costsplitter.R
  - R/get_stats.R
  - R/minimize_payments.R
  tests:
  - tests/testthat/test-check_costs.R
  - tests/testthat/test-check_participants.R
  - tests/testthat/test-cat_to_num.R
  - tests/testthat/test-get_stats.R
  - tests/testthat/test-minimize_payments.R
  - tests/testthat/test-costsplitter.R
  vignettes: vignettes/divide-costs-fairly-amongst-friends.Rmd
  inflate:
    flat_file: dev/flat_money_transfer.Rmd
    vignette_name: Divide costs fairly amongst friends
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    clean: true
