---
title: "Divide costs fairly amongst friends"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Divide costs fairly amongst friends}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

You want to use split the costs of a group activity? Here are the recommended steps

# Step 1: Think about whether you need a detailed method like this
This costsplitter method is as easy as i could make it. But there could still be easier methods. 

> First alternative method would be to do it by hand. If you did all the activities together and want to split equally its very easy to calculate. Do a small table with four colums. First is the name column. Second is the pay column - there you write what everybody paid. Third column is the share-column the total amount of expenses (sum of the pay column) divided by the total number of persons. Fourth colum is the to-pay-column which is the pay-column minus the share-column. The to-pay-column should add up to 0. Then with a bit of thinking you can finde ways to say who pays to whom

> Second alternative method is to use a dedicated app or webpage. Have a look at [https://www.kittysplit.com/](https://www.kittysplit.com/) and say hello to my Berlin fellow programmers


The costsplitter package is something for you have more difficult situation:  

* Partial participation (e.g., leaving early or joining late)
* Involvement in only select activities
* Unused reservations or no-shows
* Income disparities among group members
* Age-based consumption differences (e.g., children vs. adults)


# Step 2: Prepare the data
**Prepare the input files:** This is the tricky part of the undertaking. You need to have your data in a correct format, otherwise the function will not work correctly. Use a spreadsheet that can also be helpful during the planning of the group activity. You can have a look at my [example google-sheets-template](https://docs.google.com/spreadsheets/d/1dtL-zcGSLeKAydzJiNuFTObo6JdNwtwjRM2sjQ0a1lI/edit?usp=sharing) The data should contain the following columns:  

> The `name` column. This column indicates the names of the persons involved. This is a must have column otherwise the package will throw an error. The names must be unique.  

> The `pay_` columns. These columns hold the amount that somebody paid for one activity. At least one `pay_` column must be available. Each `pay_`column must match with one `share_`column. This must be done by a corresponding part after the `_` e.g. `pay_breakfast`and `share_breakfast`. The value should be numeric. All `pay_` columns should either start with `pay_`. 
> The `share_`columns. These columns hold the share that everyone has to pay for the activity. The second part of the name after the `_` must correspond to one `pay_`column. The value can be numeric. It must be between 0 (meaning the person does not hove to pay) and 1 (meaning the person does have to pay a full share) or it can have one of the following categorical values `full`, `reduced`, `half` or `some`. These categorical values will be transformed to numerical values. NA values and empty values will be translated into 0. All `share_` columns should either start with `share_`.  

> The `group` column. Several persons can be put together to form a group. This can be indicated in this column.   

> The `age` column. This column indicates the age of the persons involved. The value should be an integer value between 0 and 120. The value could also be either `adult` or `kid`, that will be translated into 1 and 0.5 respectively. NA values and empty values will be translated into 1.    

> The `adjustment` column. To give a general bonus or malus that will apply the complete amount somebody has to pay you can use the adjustment column. This column can be numeric between 0 (indicating the person does not have to pay) and 100 (indicating 100x times the normal share). The value can also be categorical with `more` indicating that the person should pay 1.2 times more and `less` indicating that the person should pay only 0.8 of the usual amount. NA values and empty values will be translated into 1.    


# Step 3: Do the analysis
 This is the easy part. If the input files are in structured in the right way, all you need to do is run:

```r

# Load the package
library(costsplitter)

# Read in the data
data <- read.csv('your_data_set.csv')

# Do the analysis
costsplitter(data)

```

# Step 4: Communicate your findings
You will receive a table that will look something like the table below. You can photograph this and send it to the others.

```{r}

library(costsplitter)

# data("valid_trip_data", package = "costsplitter")

costsplitter(valid_trip_data, pay_by = "individual")

```
