# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

data_participants <- check_participants()
testthat::test_that("The function get stats works fine", {
  testthat::expect_equal(get_stats(data_participants)$adults, 88)
})
