# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

data_costs <- dividefair::read_costs()
testthat::test_that("read_costs works properly with internal dataset", {
  testthat::expect_equal(nrow(data_costs), 5)
})
