# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

testthat::test_that("read_data works properly with internal dataset", {
  testthat::expect_equal(get_stats(read_data())$adults, 88)
})

df <- divide_costs()
testthat::test_that("read_data works properly with internal dataset", {
  testthat::expect_equal(sum(df$to_pay), 5500)
})

