# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

library(testthat)

test_that("Valid dataset passes checks", {
  data <- data.frame(
    name = c("Alice", "Bob", "Charlie"),
    pay_breakfast = c(20, 0, 10),
    share_breakfast = c(1, "half", "full"),
    age = c(30, "kid", NA),
    adjustment = c("more", NA, "less"),
    stringsAsFactors = FALSE
  )
  
  expect_type(check_costsplitter_data(data), "list")
})

test_that("Missing 'name' column throws an error", {
  data <- data.frame(
    pay_breakfast = c(20, 0, 10),
    share_breakfast = c(1, "half", "full")
  )
  
  expect_error(check_costsplitter_data(data), "The 'name' column is missing.")
})

test_that("Duplicate 'name' values throw an error", {
  data <- data.frame(
    name = c("Alice", "Alice", "Charlie"),
    pay_breakfast = c(20, 0, 10),
    share_breakfast = c(1, "half", "full")
  )
  
  expect_error(check_costsplitter_data(data), "The 'name' column contains duplicate entries.")
})

test_that("At least one 'pay_' column is required", {
  data <- data.frame(
    name = c("Alice", "Bob", "Charlie"),
    share_breakfast = c(1, "half", "full")
  )
  
  expect_error(check_costsplitter_data(data), "At least one 'pay_' column must be present.")
})

test_that("'pay_' columns must be numeric", {
  data <- data.frame(
    name = c("Alice", "Bob", "Charlie"),
    pay_breakfast = c("twenty", 0, 10),
    share_breakfast = c(1, "half", "full")
  )
  
  expect_error(check_costsplitter_data(data), "The 'pay_breakfast' column must be numeric.")
})


