# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand


result <- costsplitter(pay_by = "group")
testthat::test_that("The function divide costs works properly with internal dataset", {
  testthat::expect_equal(sum(result$amount), 1120)
})

