# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

data_participants <- cat_to_num()
testthat::test_that("The function change categorical to numeric works fine", {
  testthat::expect_type(data_participants$age, "double")
  testthat::expect_type(data_participants$adjustment, "double")
  testthat::expect_type(data_participants$share, "double")
  testthat::expect_false(all(is.na(data_participants$share)))
  testthat::expect_false(all(is.na(data_participants$adjustment)))
  testthat::expect_false(all(is.na(data_participants$age)))
})
