# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

df <- change_categorical_to_numeric()
testthat::test_that("read_data works properly with internal dataset", {
  testthat::expect_equal(is.numeric(df$adjustment), TRUE)
})
