# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

# Test with your dataset in "inst/"
df <- read_data(path = system.file("participants.csv", package = "dividefair"))
# Apply test on my function
testthat::test_that("read_data works properly with internal dataset", {
  testthat::expect_equal(nrow(read_data(system.file("participants.csv", package = "dividefair"))), 124)
})
