# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

data_participants <- cat_to_num()
testthat::test_that("The function change categorical to numeric works fine", {
  testthat::expect_equal(is.numeric(data_participants$adjustment), TRUE)
})
