# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

# Example data for testing
example_data <- data.frame(
  participant_name = c("Alice", "Bob", "Charlie"),
  participant_age = c(25, 30, 22),
  participant_group = c("Group1", "Group2", "Group1"),
  participant_adjustment = c(0.9, 1.1, 1.0),
  cost_food = c(10, 15, 20),
  cost_transport = c(5, 7, 6)
)


testthat::test_that("check_participants renames columns correctly", {
  data <- check_participants(
    data = example_data,
    var_name = "participant_name",
    var_age = "participant_age",
    var_group = "participant_group",
    var_adjustment = "participant_adjustment",
    indicator_costs = "cost_"
  )
  
  testthat::expect_true(all(c("name", "age", "group", "adjustment", "cost_type", "share") %in% colnames(data)))
})

testthat::test_that("check_participants pivots cost columns", {
  data <- check_participants(
    data = example_data,
    var_name = "participant_name",
    var_age = "participant_age",
    var_group = "participant_group",
    var_adjustment = "participant_adjustment",
    indicator_costs = "cost_"
  )
  
  testthat::expect_equal(nrow(data), 6)  # 3 participants * 2 cost columns = 6 rows
  testthat::expect_equal(data$cost_type[1], "cost_food")
  testthat::expect_equal(data$cost_type[4], "cost_transport")
})

testthat::test_that("check_participants throws error for missing var_name", {
  testthat::expect_error(
    check_participants(
      data = example_data,
      var_name = "wrong_name",  # non-existent column
      var_age = "participant_age",
      var_group = "participant_group",
      var_adjustment = "participant_adjustment",
      indicator_costs = "cost_"
    ),
    "Column 'wrong_name' does not exist in the data"
  )
})

testthat::test_that("check_participants throws error for missing cost prefix", {
  testthat::expect_error(
    check_participants(
      data = example_data,
      var_name = "participant_name",
      var_age = "participant_age",
      var_group = "participant_group",
      var_adjustment = "participant_adjustment",
      indicator_costs = "wrong_cost_"  # no columns with this prefix
    ),
    "No cost columns found with the prefix 'wrong_cost_'"
  )
})

testthat::test_that("check_participants throws error for empty indicator_costs", {
  testthat::expect_error(
    check_participants(
      data = example_data,
      var_name = "participant_name",
      var_age = "participant_age",
      var_group = "participant_group",
      var_adjustment = "participant_adjustment",
      indicator_costs = ""
    ),
    "The 'indicator_costs' argument is empty"
  )
})



