# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

data_participants <- divide_costs()
testthat::test_that("The function divide costs works properly with internal dataset", {
  testthat::expect_equal(sum(data_participants$to_pay), 5500)
})
