# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

# Test with your dataset in "inst/"
data_participants <- read_participants()
data_costs <- dividefair::read_costs()
# Apply test on my function
testthat::test_that("read_participants works properly with internal dataset", {
  testthat::expect_equal(nrow(data_participants), 124)
})

# testthat::test_that("All IDs in costs are also in the participants file ", {
#   testthat::expect_true(all(data_costs$id %in% data_participants$id))
# })

