# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

example_costs <- data.frame(
  id = c(10, 10, 4, 12, 4),
  name = c("Charlotte Brown", "Charlotte Brown", "Amelia Taylor", "Mia Davis", "Amelia Taylor"),
  group = c("Brown", "Brown", "Smith", "Davis", "Smith"),
  unit = c("day1", "day2", "day3", "dinnerday1", "day1"),
  cost = c(400, 900, 800, 320, 400)
)

library(testthat)

test_that("check_costs works with valid data", {
  data <- check_costs(data = example_costs)
  
  expect_true(all(c("name", "unit", "cost") %in% colnames(data)))
  expect_true(is.numeric(data$cost))
})

test_that("check_costs throws error for missing required columns", {
  # Create invalid data (remove 'cost' column)
  invalid_data <- example_costs %>% select(-cost)
  
  expect_error(check_costs(data = invalid_data), "The following required columns are missing: cost")
})

test_that("check_costs throws error if cost is not numeric", {
  # Create invalid data (change 'cost' to character)
  invalid_data <- example_costs
  invalid_data$cost <- as.character(invalid_data$cost)
  
  expect_error(check_costs(data = invalid_data), "'cost' column must be numeric")
})

