# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Convert Categorical Values to Numeric
#'
#' This function converts various categorical values within the dataset to numeric values, 
#' particularly for cost shares and age adjustments, as per the parameters provided. 
#' It processes specific columns like age and adjustment to create numeric equivalents, 
#' enabling further analysis and computation within the `costsplitter` package.
#'
#' @param data A data frame, typically the output of \code{check_costsplitter_data()}, containing the cost and participant information. 
#' Defaults to \code{check_costsplitter_data()} if not provided.
#' @param age_adjustment A numeric value used to scale age values to proportions. Default is \code{1/18}.
#' @param share_adult A numeric value indicating the proportion for adults. Default is \code{1}.
#' @param share_kid A numeric value indicating the proportion for kids. Default is \code{0.5}.
#' @param share_full A numeric value representing the full share for participants. Default is \code{1}.
#' @param share_reduced A numeric value representing the reduced share for participants. Default is \code{0.7}.
#' @param share_less A numeric value representing a discounted share applied to participants with the "less" category. Default is \code{0.8}.
#' @param share_more A numeric value representing an increased share applied to participants with the "more" category. Default is \code{1.2}.
#' 
#' @return A data frame with transformed numeric values for age, adjustment, and other relevant columns.
#'
#' @details The function handles several transformations:
#' \itemize{
#'   \item Categorical values in cost columns (e.g., "full", "reduced") are converted to numeric.
#'   \item Age values are translated based on adult and kid patterns in both English and German.
#'   \item The adjustment column is converted to numeric based on predefined categories like "more" and "less."
#' }
#'
#'
#' @export
#' @examples
#' data_participants = check_costsplitter_data() |> cat_to_num()
#'
cat_to_num <- function(data = check_costsplitter_data(),
                       age_adjustment = (1 / 18),
                       share_adult = 1,
                       share_kid = 0.5,
                       share_full = 1, 
                       share_reduced = 0.7, 
                       share_less = 0.8, 
                       share_more = 1.2) {
  
  # Convert shares to characters for case_when
  share_reduced_character = as.character(share_reduced)
  share_adult_character = as.character(share_adult * 18)
  share_kid_character = as.character(share_kid * 18)
  share_full_character = as.character(share_full)
  share_less_character = as.character(share_less)
  share_more_character = as.character(share_more)
  
  # Define patterns for adults and kids in both English and German
  adult_patterns <- tolower(c("adult", "adults", "erwachsene", "erwachsenen"))
  kid_patterns <- tolower(c("kid", "kids", "kind", "kinder"))

  data <- data |>
    mutate(across(starts_with("cost_"), ~ as.numeric(case_when(
      is.na(.) | . == "" ~ "0",
      . == "full" ~ "1",
      . == "reduced" ~ share_reduced_character,
      TRUE ~ .
    )))) |>
    # Age
    dplyr::mutate(age = dplyr::case_when(
      is.na(.data$age) | .data$age == "" ~ "18",
      .data$age %in% adult_patterns ~ share_adult_character,
      .data$age %in% kid_patterns ~ share_kid_character,
      TRUE ~ .data$age
    )) |> 
    dplyr::mutate(age = as.numeric(.data$age)) |> 
    dplyr::mutate(age = round(.data$age * age_adjustment, 2)) |>
    # Adjustment
    dplyr::mutate(adjustment = dplyr::case_when(
      is.na(.data$adjustment) | .data$adjustment == "" ~ "1",
      .data$adjustment == "more" ~ share_more_character,
      .data$adjustment == "less" ~ share_less_character,
      TRUE ~ .data$adjustment
    )) |>
    dplyr::mutate(adjustment = as.numeric(.data$adjustment)) 
  
  return(data)
}
