# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Change Categorical Values to Numeric
#'
#' This function converts categorical descriptive values in the columns `share`, `adjustment`, and `age` to numeric values.
#'
#' @param data_participants A dataframe containing the columns `share`, `adjustment`, and `age`.
#' @param share_reduced A numeric value to assign when `share` is "reduced". Default is `0.7`.
#' @param adjustment_less A numeric value to assign when `adjustment` is "less". Default is `0.8`.
#' @param adjustment_more A numeric value to assign when `adjustment` is "more". Default is `1.2`.
#'
#' @return A dataframe with transformed values.
#' @export
#' @examples
#' data_participants = check_participants()
#' data_participants2 <- cat_to_num(data_participants)
cat_to_num <- function(data = check_participants(),
                       age_adjustment = (1 / 18),
                       share_adult = 1,
                       share_kid = 0.5,
                       share_full = 1, 
                       share_reduced = 0.7, 
                       share_less = 0.8, 
                       share_more = 1.2) {
  
  
  # Define patterns for adults and kids in both English and German
  adult_patterns <- tolower(c("adult", "adults", "erwachsene", "erwachsenen"))
  kid_patterns <- tolower(c("kid", "kids", "kind", "kinder"))
  
  # Keep in mind the case_when needs character on both sides. 
  share_reduced_character = as.character(share_reduced)
  share_adult_character = as.character(share_adult * 18 )
  share_kid_character = as.character(share_kid * 18)
  share_full_character = as.character(share_full)
  share_reduced_character = as.character(share_reduced)
  share_less_character = as.character(share_less)
  share_more_character = as.character(share_more)
  
  # Change the categorical values to numerical values
  data <- data %>%
    # Age
    dplyr::mutate(age = dplyr::case_when(
      is.na(age) | age == "" ~ "18",
      age %in% adult_patterns ~ share_adult_character,
      age %in% kid_patterns ~ share_kid_character,
      TRUE ~ age 
    )) |> 
    dplyr::mutate(age = as.numeric(age)) |> 
    dplyr::mutate(age = round(age * age_adjustment, 2)) |> 
    # Share
    dplyr::mutate(share = dplyr::case_when(
      is.na(share) | share == "" ~ "0",  
      share == "full" ~ "1",
      share == "reduced" ~ "0.7",
      TRUE ~ share
    )) |>
    dplyr::mutate(share = as.numeric(share)) |> 
    # Adjustment
    dplyr::mutate(adjustment = dplyr::case_when(
      is.na(adjustment) | adjustment == "" ~ "1",
      adjustment == "more" ~ share_more_character,
      adjustment == "less" ~ share_less_character,
      TRUE ~ adjustment
    )) |>
    dplyr::mutate(adjustment = as.numeric(adjustment)) 
  
  return(data)
}
