# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Change Categorical Values to Numeric
#'
#' This function converts categorical descriptive values in the columns `share`, `adjustment`, and `age` to numeric values.
#'
#' @param data_participants A dataframe containing the columns `share`, `adjustment`, and `age`. Default is `data_participants`.
#' @param share_reduced A string representing the numeric value to assign when `share` is "reduced". Default is `"0.7"`.
#' @param adjustment_less A string representing the numeric value to assign when `adjustment` is "less". Default is `"0.8"`.
#' @param adjustment_more A string representing the numeric value to assign when `adjustment` is "more". Default is `"1.2"`.
#'
#' @return A dataframe with the `share`, `adjustment`, and `age` columns transformed to numeric values, replacing descriptive values with specified numeric equivalents.
#' @details The function transforms:
#'   - The `share` column: "full" becomes `1`, "reduced" becomes the value of `share_reduced`, and `NA` values become `0`. 
#'   - The `adjustment` column: "more" becomes the value of `adjustment_more`, "less" becomes the value of `adjustment_less`, and `NA` values become `1`.
#'   - The `age` column: `NA` values are replaced with `18`.
#'
#' @export
#' @examples
#' data_participants <- change_categorical_to_numeric()
change_categorical_to_numeric <- function(data_participants = read_participants(), 
                                          share_reduced = 0.7, 
                                          adjustment_less = 0.8, 
                                          adjustment_more = 1.2) {
  
  # Keep in mind the case_when needs character on both sides. 
  share_reduced = as.character(share_reduced)
  adjustment_less = as.character(adjustment_less)
  adjustment_more = as.character(adjustment_more)
  
data_participants |> 
    dplyr::mutate(share = dplyr::case_when(
      is.na(.data$share) ~ "0",  
      .data$share == "full" ~ "1",
      .data$share == "reduced" ~ "0.7",
      TRUE ~ .data$share
    )) |>
    dplyr::mutate(share = as.numeric(.data$share)) |> 
  dplyr::mutate(adjustment = dplyr::case_when(
    .data$adjustment == "more" ~ adjustment_more,
    .data$adjustment == "less" ~ adjustment_less,
    is.na(.data$adjustment) ~ "1",
    TRUE ~ .data$adjustment
    )) |>
  dplyr::mutate(adjustment = as.numeric(.data$adjustment)) |> 
    dplyr::mutate(age = dplyr::case_when(
      is.na(.data$age) ~ 18,
      TRUE ~ as.numeric(.data$age)
    ))
}
