# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Check the dataset for conformity with costsplitter prerequisites
#'
#' This function checks whether a given dataset conforms to the expected format and requirements
#' of the `costsplitter` package. It ensures the presence and validity of required columns such
#' as `name`, `pay_`, `share_`, `group`, `age`, and `adjustment`.
#'
#' @param data A data frame containing the cost-sharing data.
#' @param var_pay A string indicating the prefix for payment columns (default is "pay_").
#' @param var_share A string indicating the prefix for share columns (default is "share_").
#' @param value_full A numeric value representing the full share (default is 1).
#' @param value_reduced A numeric value representing the reduced share (default is 0.8).
#' @param value_half A numeric value representing the half share (default is 0.5).
#' @param value_some A numeric value representing the partial share (default is 0.3).
#'
#' @return A message indicating whether the dataset conforms to `costsplitter` prerequisites.
#'         Stops execution if the dataset does not conform.
#' @export
#' @examples
#' library(dplyr)
#' library(stringr)
#' data <- data.frame(
#'   name = c("Alice", "Bob", "Charlie"),
#'   pay_breakfast = c(20, 0, 10),
#'   share_breakfast = c(1, "half", "full"),
#'   age = c(30, "kid", NA),
#'   adjustment = c("more", NA, "less")
#' )
#'
#' check_costsplitter_data(data)
#'
check_costsplitter_data <- function(data = readr::read_csv(system.file("participants.csv", package = "costsplitter"), show_col_types = FALSE), 
                                    var_pay = "pay_", 
                                    var_share = "share_",
                                    value_full = 1, 
                                    value_reduced = 0.8, 
                                    value_half = 0.5, 
                                    value_some = 0.3) {
  
  # Check if 'name' column exists and is unique
  if (!"name" %in% colnames(data)) {
    stop("The 'name' column is missing.")
  }

  if (anyDuplicated(data$name)) {
    stop("The 'name' column contains duplicate entries.")
  }

  # Check for at least one 'pay_' column
  pay_cols <- grep(paste0("^", var_pay), colnames(data), value = TRUE)
  if (length(pay_cols) == 0) {
    stop("At least one 'pay_' column must be present.")
  }

  # Validate 'pay_' columns (should be numeric)
  for (pay_col in pay_cols) {
    if (!is.numeric(data[[pay_col]])) {
      stop(paste("The '", pay_col, "' column must be numeric.", sep = ""))
    }
  }

    # Get all 'share_' columns
  share_cols <- data %>%
    select(starts_with(var_share)) %>%
    colnames()
  

  # Validate 'age' column
  if ("age" %in% colnames(data)) {
    age_values <- data$age
    if (all(age_values %in% c(NA, "", "adult", "kid") | (is.numeric(age_values) & age_values <= 0 & age_values >= 120))) {
      stop("The 'age' column must be a number between 0 and 120, or 'adult' or 'kid'.")
    }
  }

  # Validate 'adjustment' column
  if ("adjustment" %in% colnames(data)) {
    adjustment_values <- data$adjustment
    if (all(!(adjustment_values %in% c(NA, "", "more", "less")) | (is.numeric(adjustment_values) & adjustment_values <= 0 & adjustment_values >= 100))) {
      stop("The 'adjustment' column must be a number between 0 and 100 or categorical ('more', 'less').")
    }
  }

  return(data)
}

