# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Read and Process Participant Data from CSV
#'
#' This function reads a CSV file containing participant data, cleans and processes it,
#' and returns a tidy data frame. It allows for flexible column naming and handles
#' various CSV structures.
#'
#' @param participants_df A string. The file path to the CSV file.
#' @param var_id A string. The name of the ID column in the CSV (default: "id").
#' @param var_age A string. The name of the age column in the CSV (default: "age").
#' @param var_group A string. The name of the group column in the CSV (default: "group").
#' @param var_adjustment A string. The name of the adjustment column in the CSV (default: "adjustment").
#' @param indicator_costs A string. The prefix for cost columns in the CSV (default: "cost_").
#' @param var_agegroup A string. The name of the age group column in the CSV (default: "agegroup").
#' @param value_adults A string. The value to use for adult age groups (default: "adult").
#' @param value_kids A string. The value to use for kid age groups (default: "kid").
#'
#' @return A tibble (data frame) containing the processed participant data.
#'
#' @details
#' The function performs the following operations:
#' 1. Reads the CSV file
#' 2. Cleans column names
#' 3. Renames columns based on user-provided names
#' 4. Processes the age group column, categorizing into adults and kids
#' 5. Pivots cost columns into a long format
#'
#'
#' @import dplyr
#' @import tidyr
#' @import readr
#' @import janitor
#' @importFrom rlang sym
#'
#' @export
#' @examples
#' data_participants <- check_participants()
#'
check_participants <- function(participants_df = read.csv(system.file("participants.csv", package = "costsplitter")),
                              var_name = "name",
                              var_age = "age",
                              var_group = "group",
                              var_adjustment = "adjustment",
                              indicator_costs = "cost_") {
  
  
  # Assert that the provided columns exist in the data
  if (!var_name %in% colnames(participants_df)) {
    rlang::abort(glue::glue("Column '{var_name}' does not exist in the data. Please check the variable name."))
  }
  if (!var_age %in% colnames(participants_df)) {
    rlang::abort(glue::glue("Column '{var_age}' does not exist in the data. Please check the variable name."))
  }
  if (!var_group %in% colnames(participants_df)) {
    rlang::abort(glue::glue("Column '{var_group}' does not exist in the data. Please check the variable name."))
  }
  if (!var_adjustment %in% colnames(participants_df)) {
    rlang::abort(glue::glue("Column '{var_adjustment}' does not exist in the data. Please check the variable name."))
  }
  
  # Assert that indicator_costs is not empty
  if (nchar(indicator_costs) == 0) {
    rlang::abort("The 'indicator_costs' argument is empty. Please provide a valid prefix for cost columns.")
  }
  
  # Rename columns based on user-provided names
  participants_df <- participants_df %>%
    rename(
      name = all_of(var_name),
      age = all_of(var_age),
      group = all_of(var_group),
      adjustment = all_of(var_adjustment)
    )
  
  # Identify cost columns
  cost_cols <- grep(paste0("^", indicator_costs), colnames(participants_df), value = TRUE)
  
    # Assert that there is at least one cost column
  if (length(cost_cols) == 0) {
    rlang::abort(glue::glue("No cost columns found with the prefix '{indicator_costs}'. Please check the prefix."))
  }
  
  
  # Pivot longer for cost columns
  participants_df <- participants_df %>%
    tidyr::pivot_longer(all_of(cost_cols), names_to = "cost_type", values_to = "share")
  
  return(participants_df)
}

