# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Read and check cost data 
#'
#' This function reads cost data from a dataset and checks if it works for the pourpose of this package.
#'
#' 
#' @param cost_df A character string specifying data. Defaults to the read.csv(system.file("costs.csv", package = "costsplitter")), which is the file included in the costsplitter package.
#'
#' @return A tibble containing the cost data read from the CSV file.
#'
#' @importFrom rlang abort
#' @importFrom glue glue
#'
#' @export
#' @examples
#' data_costs <- costsplitter::check_costs()
check_costs <- function(cost_df = read.csv(system.file("costs.csv", package = "costsplitter"))) {
  
  # Assert that the required columns are present
  required_columns <- c("name", "unit", "cost")
  
  missing_columns <- setdiff(required_columns, colnames(cost_df))
  
  if (length(missing_columns) > 0) {
    rlang::abort(glue::glue("The following required columns are missing: {paste(missing_columns, collapse = ', ')}"))
  }
  
  # Assert that 'cost' is numeric
  if (!is.numeric(cost_df$cost)) {
    rlang::abort("'cost' column must be numeric.")
  }

  # Return data
  return(tibble(cost_df))
}

