# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Divide Costs Fairly Among Participants
#'
#' This function calculates the fair division of costs among participants based on their weights.
#' It reads the participants' and costs' data from files, calculates the total costs for each participant or group,
#' and returns the amounts to be paid after applying any payments that have already been made.
#'
#' @param data The dataset 
#' @param pay_by A string specifying whether to divide costs by "group" or "individual". Defaults to "group".
#'
#' @return A data frame containing the final payments for each person or group after minimizing the payments.
#'
#'
#' @import dplyr tidyr
#' @export
#' @examples
#' result <- costsplitter(pay_by = "group")
costsplitter <- function(data = readr::read_csv(system.file("participants.csv", package = "costsplitter"), show_col_types = FALSE), 
                         pay_by = "individual"){

    # Reading in the data
    data <- readr::read_csv(system.file("participants.csv", package = "costsplitter"), show_col_types = FALSE) |>
        check_costsplitter_data() |> 
        cat_to_num() |>
        dplyr::mutate(across(starts_with("cost_"), ~ . * .data$age * .data$adjustment)) 

    # Split the dataset into participants data and a dataset showing what everybody paid
    data_participants <- data |> 
        dplyr::select(.data$name, .data$group, dplyr::starts_with("cost_")) |>
        tidyr::pivot_longer(cols = dplyr::starts_with("cost_"), names_to = "activity", values_to = "costs") |>
        dplyr::mutate(activity = stringr::str_split_i(.data$activity, pattern = "_", 2))

    data_costs <- dplyr::left_join(
        names(data) |> 
            stringr::str_subset("^cost_") |> 
            purrr::map_dfr(~ data |> 
                dplyr::summarise(activity = .x, total_units = sum(.data[[.x]], na.rm = TRUE))) |>
            dplyr::mutate(activity = stringr::str_remove(.data$activity, "^cost_")),
        names(data) |> 
            stringr::str_subset("^pay_") |>
            purrr::map_dfr(~ data |> 
                dplyr::summarise(activity = .x, total_payed = sum(.data[[.x]], na.rm = TRUE))) |>
            dplyr::mutate(activity = stringr::str_remove(.data$activity, "^pay_")), by = "activity"
    ) |> 
    dplyr::mutate(cost_per_unit = .data$total_payed / .data$total_units) |>
    dplyr::select(.data$activity, .data$cost_per_unit)

    # Combine the dataset
    data_topay <- data_participants |>
        dplyr::left_join(data_costs, by = "activity") |>
        dplyr::mutate(topay = .data$costs * .data$cost_per_unit)

    # Get the data_topay and data_recieves
    data_topay <- if(pay_by == "group"){
        data_topay |>
            dplyr::group_by(.data$group) |>
            dplyr::summarise(to_pay = sum(.data$topay)) |>
            dplyr::rename(element = .data$group)
    } else {
        data_topay |>
            dplyr::group_by(.data$name) |>
            dplyr::summarise(to_pay = sum(.data$topay)) |>
            dplyr::rename(element = .data$name)
    }

    data_recieves <- if(pay_by == "group"){
        data |>
            dplyr::select(.data$group, dplyr::starts_with("pay_")) |>
            tidyr::pivot_longer(cols = dplyr::starts_with("pay"), names_to = "activity", values_to = "payed") |>
            dplyr::group_by(.data$group) |>
            dplyr::summarise(recieves = sum(.data$payed, na.rm = TRUE)) |>
            dplyr::rename(element = .data$group)
    } else {
        data |>
            dplyr::select(.data$name, dplyr::starts_with("pay_")) |>
            tidyr::pivot_longer(cols = dplyr::starts_with("pay"), names_to = "activity", values_to = "payed") |>
            dplyr::group_by(.data$name) |>
            dplyr::summarise(recieves = sum(.data$payed, na.rm = TRUE)) |>
            dplyr::rename(element = .data$name)
    }

    # Combine the data again
    data_tosplit <- data_topay |> 
        dplyr::left_join(data_recieves, by = "element") |>
        dplyr::mutate(to_pay = .data$to_pay - .data$recieves) |>
        dplyr::select(.data$element, .data$to_pay)

    # Apply the minimization function from above
    results <- minimize_payments(data_tosplit) 

    return(results)
}
