# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Divide Costs Fairly Among Participants
#'
#' This function calculates the fair division of costs among participants based on their weights.
#' It reads the participants' and costs' data from files, calculates the total costs for each participant or group,
#' and returns the amounts to be paid after applying any payments that have already been made.
#'
#' @param participants_file Path to the CSV file containing participants' information. Defaults to a file within the package.
#' @param costs_file Path to the CSV file containing costs' information. Defaults to a file within the package.
#' @param pay_by A string specifying whether to divide costs by "group" or "individual". Defaults to "group".
#'
#' @return A data frame containing the final payments for each person or group after minimizing the payments.
#'
#' @details
#' The function starts by reading the participants and costs data. It calculates the total costs and
#' distributes them based on the participants' weights. It also considers the payments already made.
#' Depending on the `pay_by` argument, costs are divided either by group or by individual. The final step
#' involves minimizing the payments using the `minimize_payments` function.
#'
#' @import dplyr tidyr
#' @export
#' @examples
#' result <- divide_fairly(pay_by = "group")
divide_fairly <- function(participants_file = system.file("participants.csv", package = "dividefair"), 
                          costs_file = system.file("costs.csv", package = "dividefair"),
                          pay_by = "group"){

  # Reading in the data
  data_participants <- read_participants() |> 
    change_categorical_to_numeric() |> 
    divide_costs()
  data_costs <- read_costs()
  
  # Doing first calculations
  total_costs <- sum(data_costs$cost)
  total_weights <- sum(data_participants$weight)
  cost_per_weight <- total_costs / total_weights
  
  # Calculate costs_produced
  data_participants <- data_participants |> 
    dplyr::mutate(costs_produced = .data$weight * cost_per_weight) 
  
  # Summarise and add the costs
  if (pay_by == "group") {
    df <- data_participants |> 
      dplyr::group_by(.data$group) |> 
      dplyr::summarise(costs_produced = sum(.data$costs_produced))|> 
      dplyr::left_join(
        data_costs |> 
          dplyr::group_by(.data$group) |> 
          dplyr::summarise(payed = sum(.data$cost)),
        by = "group"
      ) |> 
      dplyr::mutate(payed = tidyr::replace_na(.data$payed, 0)) |> 
      dplyr::mutate(to_pay_unrounded = .data$costs_produced - .data$payed) |> 
      dplyr::mutate(to_pay = round(.data$to_pay_unrounded / 5) * 5) |> 
      dplyr::mutate(person = .data$group)
  } else if (pay_by == "individual") {
    df <- data_participants |> 
      dplyr::group_by(.data$id) |> 
      dplyr::summarise(costs_produced = sum(.data$costs_produced))|> 
      dplyr::left_join(
        data_costs |> 
          dplyr::group_by(.data$id) |> 
          dplyr::summarise(payed = sum(.data$cost)),
        by = "id"
      ) |> 
      dplyr::mutate(payed = tidyr::replace_na(.data$payed, 0)) |> 
      dplyr::mutate(to_pay_unrounded = .data$costs_produced - .data$payed) |> 
      dplyr::mutate(to_pay = round(.data$to_pay_unrounded / 5) * 5) |> 
      dplyr::mutate(person = as.character(.data$id))
  }
  
  # Apply the minimize_payment function
  results <- minimize_payments(df |> dplyr::select(.data$person, .data$to_pay))
  
  return(results)
}



