# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Divide Costs Based on Weighted Factors
#'
#' This function calculates how much each individual should pay, based on various weighted factors such as age group, adjustment, and presence.
#'
#' @param data_participants A dataframe containing the columns `agegroup`, `age`, `adjustment`, and `share`. Default is `data_participants`.
#' @param cost The total cost to be divided among individuals. Default is `5500`.
#'
#' @return A dataframe with an additional column `costs_produced`, representing the calculated cost each individual needs to pay based on their weight.
#' @details The function computes a `weight` for each individual based on:
#'   - Initializing `weight` to `1`.
#'   - If `agegroup` is `"kid"`, the weight is updated to `weight * 0.0555 * age`.
#'   - The weight is further multiplied by values in `adjustment` and `share` columns.
#'   - The total cost (`cost`) is divided based on the sum of weights to determine each individual's share.
#'
#' @importFrom dplyr mutate case_when
#' @export
#' @examples
#' data_participants <- divide_costs()
divide_costs <- function(data_participants = read_participants() |> change_categorical_to_numeric()) {
  data_participants |> 
    dplyr::mutate(weight = 1) |> 
    dplyr::mutate(weight = dplyr::case_when(
      .data$agegroup == "kid" ~ .data$weight * 0.0555 * .data$age,
      TRUE ~ .data$weight
    )) |> 
    dplyr::mutate(weight = .data$weight * .data$adjustment) |> 
    dplyr::mutate(weight = .data$weight * .data$share) |> 
    dplyr::mutate(weight = as.numeric(.data$weight)) 
}
