# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand


# Test if the function runs without error for categorical values
testthat::test_that("Check that helper_process_adjustment runs without error for categorical values", {
  df <- valid_trip_data
  df$adjustment <- c("more", "more", "less", "less", "more")
  testthat::expect_no_error(helper_process_adjustment(df))
})

# Test if the function runs without error for numeric values within range
testthat::test_that("Check that helper_process_adjustment runs without error for numeric values within range", {
  df <- valid_trip_data
  df$adjustment <- c(0, 10, 50, 70, 100)
  testthat::expect_no_error(helper_process_adjustment(df))
})

# Test if the function runs without error for a mix of numeric and categorical values
testthat::test_that("Check that helper_process_adjustment runs without error for a mix of numeric and categorical values", {
  df <- valid_trip_data
  df$adjustment <- c(10, "more", "less", 80, 0)
  testthat::expect_no_error(helper_process_adjustment(df))
})

# Test if the function runs without error when there are NA values
testthat::test_that("Check that helper_process_adjustment runs without error for NA values", {
  df <- valid_trip_data
  df$adjustment <- c(20, NA, "more", "", "less")
  testthat::expect_no_error(helper_process_adjustment(df))
})

# Test if the function output contains only the 'name' and 'adjustment' columns (since no pivoting is applied here)
testthat::test_that("Output contains only 'name' and 'adjustment'", {
  # Example output from your function
  df <- helper_process_adjustment(valid_trip_data)
  
  # Get the names of the expected columns
  expected_columns <- c("name", "activity", "adjustment")
  
  # Test if the column names are exactly as expected
  testthat::expect_named(df, expected_columns)
})

