# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Get Statistics on Participants
#'
#' This function calculates statistics regarding the number of adults, children, stays, and absences
#' in a given data frame based on the `agegroup` and `share` columns.
#'
#' @param data_participants A data frame containing at least the following columns:
#'   - `agegroup`: A character vector indicating whether the participant is an "adult" or a "kid".
#'   - `share`: A character vector indicating presence with values "x" for stays and "n" for absences.
#'
#' @return A list containing:
#'   - `adults`: The total number of adults in the data frame.
#'   - `children`: The total number of children in the data frame.
#'
#'
#' @export
#' @examples
#' stats <- get_stats(read_participants())
#'
get_stats <- function(data_participants = read_participants()) {
  stats <- list()
  stats$adults <- sum(data_participants$agegroup == "adult" , na.rm = TRUE)
  stats$children <- sum(data_participants$agegroup == "kid", na.rm = TRUE)
  return(stats)
}
