# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Divide Costs Based on Weighted Factors
#'
#' This function calculates how much each individual should pay, based on various weighted factors such as age group, adjustment, and presence.
#'
#' @param df A dataframe containing the columns `agegroup`, `age`, `adjustment`, and `present`. Default is `df`.
#' @param cost The total cost to be divided among individuals. Default is `5500`.
#'
#' @return A dataframe with an additional column `to_pay`, representing the calculated cost each individual needs to pay based on their weight.
#' @details The function computes a `weight` for each individual based on:
#'   - Initializing `weight` to `1`.
#'   - If `agegroup` is `"kid"`, the weight is updated to `weight * 0.0555 * age`.
#'   - The weight is further multiplied by values in `adjustment` and `present` columns.
#'   - The total cost (`cost`) is divided based on the sum of weights to determine each individual's share.
#'
#' @importFrom dplyr mutate case_when
#' @export
#' @examples
#' df <- divide_costs()
divide_costs <- function(df = read_data() |> change_categorical_to_numeric(), cost = 5500) {
  df |> 
    dplyr::mutate(weight = 1) |> 
    dplyr::mutate(weight = dplyr::case_when(
      agegroup == "kid" ~ weight * 0.0555 * age,
      TRUE ~ weight
    )) |> 
    dplyr::mutate(weight = weight * adjustment) |> 
    dplyr::mutate(weight = weight * present) |> 
    dplyr::mutate(weight = as.numeric(weight)) |> 
    dplyr::mutate(to_pay = (weight * 5500) / sum(weight, na.rm = TRUE))
}

#' Get Statistics on Participants
#'
#' This function calculates statistics regarding the number of adults, children, stays, and absences
#' in a given data frame based on the `agegroup` and `present` columns.
#'
#' @param df A data frame containing at least the following columns:
#'   - `agegroup`: A character vector indicating whether the participant is an "adult" or a "kid".
#'   - `present`: A character vector indicating presence with values "x" for stays and "n" for absences.
#'
#' @return A list containing:
#'   - `adults`: The total number of adults in the data frame.
#'   - `children`: The total number of children in the data frame.
#'   - `no_of_stays`: The total number of stays indicated by "x" in the `present` column.
#'   - `no_of_absences`: The total number of absences indicated by "n" in the `present` column.
#'
#'
#' @export
#' @examples
#' get_stats(read_data())
#'
get_stats <- function(df = read_data()) {
  stats <- list()
  stats$adults <- sum(df$agegroup == "adult" , na.rm = TRUE)
  stats$children <- sum(df$agegroup == "kid", na.rm = TRUE)
  return(stats)
}
