# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Read data
#'
#' @param path A file path to the participant.csv file
#'
#' @return
#' a data frame
#' @export
#'
#' @importFrom dplyr mutate case_when
#' @importFrom tidyr pivot_longer
#' @importFrom  readr read_csv
#' @importFrom  janitor clean_names
#' @examples
#' df <- read_data(path = system.file("participants.csv", package = "dividefair"))
#'
read_data <- function(path = system.file("participants.csv", package = "dividefair"),
                      var_agegroup = "agegroup",
                      value_adults = "adult",
                      value_kids = "kid",
                      indicator_costs = "cost",
                      var_present = "present") {
  
   
  # Define patterns for adults and kids in both English and German
  adult_patterns <- tolower(c("adult", "adults", "erwachsene", "erwachsenen"))
  kid_patterns <- tolower(c("kid", "kids", "kind", "kinder")) 

  readr::read_csv(path, show_col_types = FALSE) |> 
    janitor::clean_names() |> 
    dplyr::rename(!!var_agegroup := agegroup) |>
    dplyr::mutate(!!var_agegroup := dplyr::case_when(
      tolower(!!dplyr::sym(var_agegroup)) %in% adult_patterns ~ value_adults,
      tolower(!!dplyr::sym(var_agegroup)) %in% kid_patterns ~ value_kids,
      TRUE ~ !!dplyr::sym(var_agegroup) # Keep the original value if it doesn't match
    )) |> 
    tidyr::pivot_longer(starts_with(indicator_costs), names_to = indicator_costs, values_to = var_present)
}

