# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Read and Process Participant Data from CSV
#'
#' This function reads a CSV file containing participant data, cleans and processes it,
#' and returns a tidy data frame. It allows for flexible column naming and handles
#' various CSV structures.
#'
#' @param path A string. The file path to the CSV file.
#' @param var_id A string. The name of the ID column in the CSV (default: "id").
#' @param var_age A string. The name of the age column in the CSV (default: "age").
#' @param var_group A string. The name of the group column in the CSV (default: "group").
#' @param var_adjustment A string. The name of the adjustment column in the CSV (default: "adjustment").
#' @param indicator_costs A string. The prefix for cost columns in the CSV (default: "cost_").
#' @param var_agegroup A string. The name of the age group column in the CSV (default: "agegroup").
#' @param value_adults A string. The value to use for adult age groups (default: "adult").
#' @param value_kids A string. The value to use for kid age groups (default: "kid").
#'
#' @return A tibble (data frame) containing the processed participant data.
#'
#' @details
#' The function performs the following operations:
#' 1. Reads the CSV file
#' 2. Cleans column names
#' 3. Renames columns based on user-provided names
#' 4. Processes the age group column, categorizing into adults and kids
#' 5. Pivots cost columns into a long format
#'
#'
#' @import dplyr
#' @import tidyr
#' @import readr
#' @import janitor
#' @importFrom rlang sym
#'
#' @export
#' @examples
#' data_participants <- read_participants()
#'
read_participants <- function(path = system.file("participants.csv", package = "dividefair"),
                      var_id = "id",
                      var_age = "age",
                      var_group = "group",
                      var_adjustment = "adjustment",
                      var_agegroup = "agegroup",
                      indicator_costs = "cost_",
                      value_adults = "adult",
                      value_kids = "kid") {
  
  # Define patterns for adults and kids in both English and German
  adult_patterns <- tolower(c("adult", "adults", "erwachsene", "erwachsenen"))
  kid_patterns <- tolower(c("kid", "kids", "kind", "kinder"))
  
  # Read the CSV file
  data <- readr::read_csv(path, show_col_types = FALSE)
  
  # Clean column names
  data <- janitor::clean_names(data)
  
  # Rename columns based on user-provided names
  data <- data %>%
    dplyr::rename(
      id = !!rlang::sym(var_id),
      age = !!rlang::sym(var_age),
      group = !!rlang::sym(var_group),
      adjustment = !!rlang::sym(var_adjustment),
      !!var_agegroup := !!rlang::sym(var_agegroup)
    )
  
  # Process the agegroup column
  data <- data %>%
    dplyr::mutate(!!var_agegroup := dplyr::case_when(
      tolower(!!rlang::sym(var_agegroup)) %in% adult_patterns ~ value_adults,
      tolower(!!rlang::sym(var_agegroup)) %in% kid_patterns ~ value_kids,
      TRUE ~ !!rlang::sym(var_agegroup) # Keep the original value if it doesn't match
    ))
  
  # Identify cost columns
  cost_cols <- grep(paste0("^", indicator_costs), names(data), value = TRUE)
  
  # Pivot longer for cost columns
  data <- data %>%
    tidyr::pivot_longer(all_of(cost_cols), names_to = "cost_type", values_to = "share")
  
  return(data)
}


