# WARNING - Generated by {fusen} from dev/flat_money_transfer.Rmd: do not edit by hand

#' Read Cost Data from CSV File
#'
#' This function reads cost data from a CSV file, defaulting to the "costs.csv" 
#' file included in the dividefair package.
#'
#' @param path A character string specifying the path to the CSV file. 
#'   Defaults to the "costs.csv" file included in the dividefair package.
#'
#' @return A tibble containing the cost data read from the CSV file.
#'
#' @importFrom readr read_csv
#'
#' @export
#' @examples
#' data_costs <- dividefair::read_costs()
read_costs <- function(path = system.file("costs.csv", package = "dividefair")){
  readr::read_csv(path, show_col_types = FALSE) 
}
